### ISSUE TITLE
リアクションデータのカスタムフック

### ISSUE THREAD

**Issue by sts11142** [Rei1449/geekhack-vol16#6]
abst

- 絵文字、リアクションコメントを一つの型に統一して提供
- Reaction型も用意しておく
- イメージだけメモしておきます

return

- reactions: Reaction[]

Reaction's attributes

- emotion: "positive"|"negative"
- text: 絵文字|テキスト
-

**Comment by sts11142** [comment]
FYI @zackerms 

他にもこのくらいの粒度のものがあれば挙げておいて時間見つけてやっていきます！

**Comment by zackerms** [comment]
@Rei1449 助かります！　俺も、タスクを振りやすいように思いついたらissue作ります！
